version: '3'
services:
  websocket-server-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      - "5005:5005"
    container_name: websocket-server-1
    environment:
      - SERVER_PORT=8080
      - SPRING_REDIS_HOST=redis-1
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis-1
    networks:
      - salon-network

  websocket-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    container_name: websocket-server-2
    environment:
      - SERVER_PORT=8080
      - SPRING_REDIS_HOST=redis-1
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis-1
    networks:
      - salon-network

  redis-1:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - salon-network

networks:
  salon-network:
    driver: bridge
